name: Sphinx

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/**'
jobs:
  build-html:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      run: |
         pacman-key --init
         pacman -Syu --noconfirm
         pacman -S --noconfirm git python-sphinx python-pip ttf-dejavu python-sphinx-copybutton
         pip install --upgrade pip
         pip install --upgrade pydata-sphinx-theme
         cd docs
         make --no-keep-going html
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ARU-${{ github.sha }}
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html/
        keep_files: true
  build-pdf:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - uses: actions/checkout@v3
    - name: Build PDF
      run: |
         pacman-key --init
         pacman -Syu --noconfirm
         pacman -S --noconfirm texlive-latexextra texlive-fontsextra git texlive-core python-sphinx ttf-dejavu python-sphinx-copybutton
         cd docs
         make --no-keep-going latexpdf
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ARU-${{ github.sha }}
        path: docs/build/html/latex/ARU.pdf
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html/
        keep_files: true
